### ISSUE TITLE
Downloading videos problem 

### ISSUE THREAD

**Issue by KerolosAtef** [bytedance/Shot2Story#1]
After processing only few videos are works and the remaining fails to open
Could you provide a **direct link** to easy download the videos?

You already did a great work, and it will be appreciated if it's easy to use.

**Comment by youthHan** [comment]
Thank you for your interest in our work.

Can you please indicate what the issues are, like the YouTube IDs not existing, errors after splitting videos into shots or something else? so that we can help you on it.

Regarding direct downloading of the videos, we currently do not have the license to keep and distribute them.

**Comment by KerolosAtef** [comment]
Yes, there are errors after splitting videos into shots, most of the videos can't be opened using OpenCV, moviepy or even by VLC media player. 

Could you help me with a better way to get the data, Also I tied to change splitting the videos with ffmpeg and used moviepy, but also still there is huge data lost.

```python 
import moviepy.editor as me

video = me.VideoFileClip(f"data/scripts/videos/{video_name}")
clip = video.subclip(start, end)
output_path = f"data/scripts/videos_extracted/{clip_id}.mp4"
clip.write_videofile(output_path, codec="libx264", audio_codec="aac")
video.close() 
```

**Comment by youthHan** [comment]
@KerolosAtef 

Please follow the steps to provide some information so that I can help you get through this
1. The downloaded video number after executing `download_videos.py`
2. The number of videos split with duration duration from hdvila, [this line](https://github.com/bytedance/Shot2Story/blob/8134dfbe593450f66c0d710cf9df82657134f7c2/data/scripts/process_videos.py#L50) for each video downloaded in step 1. Note that this step will store videos in a subfolder `./data/videos_extracted`

Moreover, please make sure to follow the steps in [guidance](https://github.com/bytedance/Shot2Story/blob/master/DATA.md). I have further updated and validated it, so following the steps would work.

**Comment by KerolosAtef** [comment]
@youthHan  
I downloaded the data again given the updated steps : 

1-The downloaded video number  is 20694 
2-while running the file data/scripts/process_videos.py , I got this error after 12 minute 
```
 RuntimeError: Error reading ./data/videos_extracted/-k-V3ESHcfA.3.mp4...
```
3-the number of processed videos in videos_extracted is 1179

**Comment by youthHan** [comment]
> @youthHan I downloaded the data again given the updated steps :
> 
> 1-The downloaded video number is 20694 2-while running the file data/scripts/process_videos.py , I got this error after 12 minute
> 
> ```
>  RuntimeError: Error reading ./data/videos_extracted/-k-V3ESHcfA.3.mp4...
> ```
> 
> 3-the number of processed videos in videos_extracted is 1179

Please check if the video ./data/videos/-k-V3ESHcfA.mp4 or ./data/videos/-k-V3ESHcfA.mkv exists, also check ./data/videos_extracted/-k-V3ESHcfA.3.mp4.

Moreover, to proceed, you could wrap the [line](https://github.com/bytedance/Shot2Story/blob/b5f26fe318b5a463a278281345f433e829a754c7/data/scripts/process_videos.py#L54) with exception block and return `''`.

**Comment by youthHan** [comment]
Please check #5. I will close this issue due to inactivity.
